In [3]:
! pip install datasets transformers datasets

  Obtaining dependency information for datasets from https://files.pythonhosted.org/packages/7c/55/b3432f43d6d7fee999bb23a547820d74c48ec540f5f7842e41aa5d8d5f3a/datasets-2.14.6-py3-none-any.whl.metadata
  Using cached datasets-2.14.6-py3-none-any.whl.metadata (19 kB)
  Obtaining dependency information for transformers from https://files.pythonhosted.org/packages/c1/bd/f64d67df4d3b05a460f281defe830ffab6d7940b7ca98ec085e94e024781/transformers-4.34.1-py3-none-any.whl.metadata
  Using cached transformers-4.34.1-py3-none-any.whl.metadata (121 kB)
  Obtaining dependency information for tokenizers<0.15,>=0.14 from https://files.pythonhosted.org/packages/c3/29/0d9975fb739bdbefc73b6c23f335ea18e752fe6d2e91f3266a10dc8be140/tokenizers-0.14.1-cp311-none-win_amd64.whl.metadata
  Using cached tokenizers-0.14.1-cp311-none-win_amd64.whl.metadata (6.8 kB)
Using cached datasets-2.14.6-py3-none-any.whl (493 kB)
Using cached transformers-4.34.1-py3-none-any.whl (7.7 MB)
Using cached tokenizers-0.14.1-cp311-

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python311\\Scripts\\transformers-cli.exe' -> 'C:\\Python311\\Scripts\\transformers-cli.exe.deleteme'


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: C:\Python311\python.exe -m pip install --upgrade pip


In [6]:
from datasets import *
import pickle as pk
from PIL import Image


In [7]:
ds_file = open('dataset', 'rb')
dataset = pk.load(ds_file)
dataset

DatasetDict({
    train: Dataset({
        features: ['image_file_path', 'image', 'labels'],
        num_rows: 2864
    })
    test: Dataset({
        features: ['image_file_path', 'image', 'labels'],
        num_rows: 352
    })
    validate: Dataset({
        features: ['image_file_path', 'image', 'labels'],
        num_rows: 352
    })
})

In [18]:
dataset['train'][2]

{'image_file_path': 'D:\\Dataset\\breast_cancer\\jpeg\\1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297\\1-190.jpg',
 'image': <PIL.JpegImagePlugin.JpegImageFile image mode=L size=2986x5356 at 0x28EB2137BE0>,
 'labels': 'BENIGN'}

In [19]:
from transformers import ViTFeatureExtractor

model_name_or_path = 'google/vit-base-patch16-224-in21k'
feature_extractor = ViTFeatureExtractor.from_pretrained(model_name_or_path)

c:\Users\JAVIDH S\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\models\vit\feature_extraction_vit.py:28: FutureWarning: The class ViTFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ViTImageProcessor instead.
  warnings.warn(


In [20]:
def process_example(example):
    inputs = feature_extractor([x.convert("RGB") for x in example_batch['image']], return_tensors='pt')
    inputs['labels'] = example['labels']
    return inputs

In [27]:
process_example(dataset['test'][4])

ValueError: Unsupported number of image dimensions: 2

In [35]:
import numpy as np
print(np.array(dataset['train'][4]['image']))

img = dataset['train'][4]['image']


[[255 255 255 ... 237 237 237]
 [255 255 255 ... 237 237 237]
 [255 255 255 ... 237 236 236]
 ...
 [255 255 255 ... 237 236 236]
 [255 255 255 ... 237 237 237]
 [255 255 255 ... 237 237 237]]


In [40]:
image = img.convert('RGB')
data = np.array(image)

# # Create a 3D image from the 2D array of data
# image3d = Image.fromarray(data, 'RGBX')

# # Display the 3D image
# image3d.show()
